[general]
import = [
  "~/.config/alacritty/themes/themes/pastel_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
option_as_alt = "Both"
opacity = 1.0

[font]
size = 14

[font.normal]
family = "Monaspace Argon"
style = "Regular"

[font.bold]
family = "Monaspace Argon SemiWide"
style = "Bold"

[font.italic]
family = "Monaspace Argon"
style = "Italic"

[font.bold_italic]
family = "Monaspace Argon SemiWide"
style = "Bold Italic"

[scrolling]
history = 100000
multiplier = 3

[bell]
duration = 0

[cursor]
style = { blinking = "Off" }

[terminal]
shell = { program = "/bin/zsh" }

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
