language_backend: LSP

gui_log_window: false

web_dashboard: false

web_dashboard_listen_address: 127.0.0.1

web_dashboard_open_on_launch: true

jetbrains_plugin_server_address: 127.0.0.1

log_level: 20

trace_lsp_communication: false

ls_specific_settings: {}

tool_timeout: 30

excluded_tools: []

included_optional_tools: []

fixed_tools: []

default_max_tool_answer_chars: 150000

token_count_estimator: CHAR_COUNT
